Added curator-operator to the repo list
operate-first/common pull request #70
Opened 2022-02-17 17:29 UTC by gagansk

Requesting a new repository for the curator-operator project.

2022-02-17 17:29 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **schwesig** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @schwesig` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fcommon).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/common/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["schwesig"]} -->

2022-02-21 18:42 UTC, harshad16 requested changes
LGTM
few minor changes required:
1.  Please add curator-operator below here: https://github.com/operate-first/common/blob/0dfbd660850f59186a7fa311b819a9f80c65113b/github-config.yaml#L244
2.  Please add curator-operator below here: https://github.com/operate-first/common/blob/0dfbd660850f59186a7fa311b819a9f80c65113b/github-config.yaml#L281
3.  Please add curator-operator below here: https://github.com/operate-first/common/blob/0dfbd660850f59186a7fa311b819a9f80c65113b/github-config.yaml#L369
4.  Please add curator-operator below here: https://github.com/operate-first/common/blob/0dfbd660850f59186a7fa311b819a9f80c65113b/github-config.yaml#L454

2022-02-21 18:53 UTC, gagansk commented
@harshad16 I have addressed the comments.

2022-02-21 19:05 UTC, harshad16 approved these changes
/lgtm
/approve

2022-02-21 19:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/common/pull/70#pullrequestreview-889028731" title="Approved">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **schwesig** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @schwesig` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fcommon).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/common/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["schwesig"]} -->

2022-02-22 15:35 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/common/pull/70#pullrequestreview-889028731" title="Approved">harshad16</a>*, *<a href="https://github.com/operate-first/common/pull/70#issuecomment-1047920574" title="Approved">larsks</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fcommon).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/common/blob/main/OWNERS)~~ [larsks]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-22 15:36 UTC, merged